var api = {
    getMenu: '../api/get_menu',
    getPublic: '../api/get_public',
    login: '../api/login',
    getWaitShip: '../api/get_waitShip',
    getAfterSaleNumber: '../api/get_afterSaleNumber',
    getSales: '../api/get_sales',
    getSalesBalance: '../api/get_sales_balance',
    getOrderAmount: '../api/get_orderAmount',
    getRefundAmount: '../api/get_refundAmount',
    getPeople: '../api/get_people',
    getPeopleShop: '../api/get_people_shop',
    updateRemindTime: '../api/update_remind_time', // 更新订单提醒时间

    updateGoodsState: '../api/update_goodsState',
    getGoods: '../api/get_goods',
    getGoodsByCate: '../api/get_goods_by_cate',
    getCategory: '../api/get_category',
    addCategory: '../api/add_category',
    delCategory: '../api/del_category',
    updateCategorySort: '../api/update_category_sort',
    updateCategory: '../api/update_category',
    updateGoodsCategory: '../api/update_goods_category',
    updateGoodsPrice: '../api/update_goods_price',
    updateGoodsValue: '../api/update_goods_value',
    addGoods: '../api/add_goods',
    addSpecification: '../api/add_specification',
    getSpecification: '../api/get_specification',
    // getBrand: '../api/get_brand',
    // updateBrandState: '../api/update_brandState',
    // addBrand: '../api/add_brand',
    // updateBrand: '../api/update_brand',
    getParam: '../api/get_param',
    updateGoods: '../api/update_goods',
    order: '../api/order',
    getOrderBySearch: '../api/get_order_by_search',
    addLogisticsCodeToOrder: '../api/add_logistics_code_to_order', // 物流信息 阿里
    updateOrderState: '../api/update_orderState',
    updateOrderAfterSaleState: '../api/update_orderAfterSaleState',
    getAd: '../api/get_ad',
    updateAdState: '../api/update_adState',
    updateAdSort: '../api/update_adSort',
    delAd: '../api/del_ad',
    getGoodsByCategory: '../api/get_goods_by_category',
    addAd: '../api/add_ad',
    editAd: '../api/edit_ad',
    getNavigation: '../api/get_navigation',
    updateNavigation: '../api/update_navigation',
    getWaterfall: '../api/get_waterfall',
    updateWaterfall: '../api/update_waterfall',
    updateWaterfallSort: '../api/update_waterfallSort',
    getPosition: '../api/get_position',
    getAccount: '../api/get_account',
    addAccount: '../api/add_account',
    updateAccount: '../api/update_account',
    delAccount: '../api/del_account',
    getUser: '../api/get_user',
    delReview: '../api/del_review',
    updateReview: '../api/update_review',
    updateBestReview: '../api/update_best_review',
    getReview: '../api/get_review',


    getStore: '../api/get_store',
    addStore: '../api/add_store',
    updateStore: '../api/update_store',
    delStore: '../api/del_store',

    addPanicBuyingTime: '../api/add_panicBuyingTime',
    getPanicBuyingTime: '../api/get_panicBuyingTime',
    updatePanicBuyingTime: '../api/update_panicBuyingTime',
    DelPanicBuyingTime: '../api/del_panicBuyingTime',

    getPanicBuying: '../api/get_panicBuying',
    addPanicBuying: '../api/add_panicBuying',
    updatePanicBuying: '../api/update_panicBuying',
    delPanicBuying: '../api/del_panicBuying',
    // getBrunchBanner: '../api/get_brunch_banner',
    // delBrunchBanner: '../api/del_brunch_banner',
    // updateBrunchBannerStatus: '../api/update_brunch_banner_status',
    // getBrunchCategory: '../api/get_brunch_category',
    // getGoodsByBrunchCategory: '../api/get_goods_by_brunch_category',
    // addBrunchBanner: '../api/add_brunch_banner',
    // updateBrunchBannerSort: '../api/update_brunch_banner_sort',

    // restaurantGetOrderByTime: '../api/restaurant_get_order_by_time',
    // yinbaoGetTodayOrder: '../api/yinbao_get_today_order',
    // restaurantGetTodayOrder: '../api/restaurant_get_today_order'

    addCard: '../api/add_card',
    getCard: '../api/get_card',


    getDeliveryOrder: '../api/get_delivery_order',
    updateOrderStateByTradeId: '../api/update_order_state_by_trade_id',

    updateCardInfo: '../api/update_card_info',

    getGoodsBySearch: '../api/get_goods_by_search',
    getUserBySearch: '../api/get_user_by_search',
    getPanicBuyingBySearch: '../api/get_panic_buying_by_search',
    getWaterfallBySearch: "../api/get_waterfall_by_search"
}